language: c

before_script:
  - ./autogen.sh

script:
  - ./configure --enable-code-coverage && make && make check

after_success:
  - cd src/.libs && bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    packages:
    - liblzma-dev
